In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
print(a.ndim)  # Total dimensions
print(a.shape) # Shape of array
print(a.dtype) # Datatype of array
print(a.itemsize) # The size in bytes of each element of the array

1
(3,)
int32
4


In [14]:
print(np.zeros((1,2,3), dtype = "int")) 
print(np.ones((5,2,2), dtype = "str"))   # first is for number of copies

[[[0 0 0]
  [0 0 0]]]
[[['1' '1']
  ['1' '1']]

 [['1' '1']
  ['1' '1']]

 [['1' '1']
  ['1' '1']]

 [['1' '1']
  ['1' '1']]

 [['1' '1']
  ['1' '1']]]


In [15]:
np.random.randint(low = 1, high=20, size=5, dtype=int)

array([13, 16, 15, 11,  3])

In [16]:
np.random.rand(2,3) # Total numbers (shape) to generate

array([[0.45896399, 0.89709265, 0.03719708],
       [0.53518748, 0.86662002, 0.7947249 ]])

In [17]:
print(np.arange(1,50,2)) # Print a list
print(np.linspace(1,10,20)) # Print the given total values (equi-distant) within a give range 

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [18]:
# We can use +, *, -, /, @ (Matrix multiplication)

In [20]:
print("Sum: " + str(a.sum()))
print("Min: " + str(a.min()))
print("Max: " + str(a.max()))
print("Avg: " + str(a.mean()))
print("SD: " + str(a.std()))

Sum: 6
Min: 1
Max: 3
Avg: 2.0
SD: 0.816496580927726


#### Image Modification using Numpy used in Computer Vision

<li>(PIL) python image library used to view images in jupyter notebook
<li>Any img is an set array where back and white imgs are of 2 dimensions and we can make changes in colors of the picture by changing array element's values.
<li>And we can reshape our img using np.reshape function which helps us in resizing our image
<li> <b>Note:-</b> The array is of unsinged int (non-negative integers)

#### Indexing, Slicing, Iteration

In [21]:
# 1 Dimension arrays indexing works as a list
dim_1 = np.array([1, 2, 3, 4, 5])
dim_1[0:3]

array([1, 2, 3])

In [22]:
# 2 Dimension arrays indexing works as rows and columns arr[rows, cols]
dim_2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
dim_2[1:4, 2:5]

array([[ 8,  9, 10],
       [13, 14, 15]])

<b>Note:</b>- Slicing of an array also makes the changes to the original array if we chage the value in our array it also redirects ti the original array and to prevent that we use arr.copy() function
    

In [23]:
dim_2[0,0] = 0
print(dim_2) # look it changes from 1 to 0

[[ 0  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [24]:
np.array([dim_2[0,0], dim_2[1,1], dim_2[2,2]])  
# creates a new array of selected elements from an array

array([ 0,  7, 13])

In [25]:
dim_2[[0,1], [0,2]]   
# Prints (0,0)th element and (1,2)th element

array([0, 8])

<b><u>Boolean Indexing</b></u>

In [26]:
# This trick is called boolean indexing 
#(it works the same for 2d arr)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print (arr>=5)
print (arr%2==0)

[False False False False  True  True  True  True  True  True]
[False  True False  True False  True False  True False  True]


In [27]:
# Filter out our data trick (while using indexing)
# Simply put the condition in square [] brackets
print(dim_2>5)  # creates a true/false mask
print("v/s")
print(dim_2[dim_2>5]) # Filter out the false ones

[[False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
v/s
[ 6  7  8  9 10 11 12 13 14 15]


#### Importing datasets using numpy by genfromtxt() function in numpy library

In [28]:
# Using wines.csv datafile

In [29]:
# Here we skip headers as genfromtxt only read numeric data and store string data as nan values
wines = np.genfromtxt("winequality-red.csv", delimiter = ";", skip_header=True, dtype = None, names = ("fixed acidity","volatile acidity","citric acid","residual sugar","chlorides","free sulfur dioxide","total sulfur dioxide","density","pH","sulphates","alcohol","quality"))
print(wines.shape)
print()
print()
print(wines[:3])
print()
print()
#print(wines[:,[0,2,4]])  arr(rows, columns) # Print specific cols of the dataset if datasets not have headers

(1599,)


[(7.4, 0.7 , 0.  , 1.9, 0.076, 11., 34., 0.9978, 3.51, 0.56, 9.4, 5)
 (7.8, 0.88, 0.  , 2.6, 0.098, 25., 67., 0.9968, 3.2 , 0.68, 9.8, 5)
 (7.8, 0.76, 0.04, 2.3, 0.092, 15., 54., 0.997 , 3.26, 0.65, 9.8, 5)]




In [30]:
#Function can also be applied to the datsets directly by using chainning
print(wines["quality"][:].mean())
#arr[col header][row count]
# Mean of the quality column using all rows

5.6360225140712945


In [31]:
# We can also use boolean masking as well as filtering
print (wines["quality"]>1)
print (wines[wines["quality"]>1]["pH"].mean())  
# Check if quality is greater than 1 than the rows with greater quality's pH mean is taken

[ True  True  True ...  True  True  True]
3.3111131957473416


In [ ]:
# String io is a tecniques by which we can print a data with /n, /t, etc as a normal sting of python and there is asperate library in python used in text analytics